### ISSUE TITLE
Enable support for cli v7

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry-community/cf-resource#80]
When trying to use with newer cf release I am getting the following error:

```
Cloud Foundry API version 2.155.0 requires CLI version 7.0.1. You are currently on version 6.43.0+815ea2f3d.2019-02-20. To upgrade your CLI, please visit: https://github.com/cloudfoundry/cli#downloads

```

**Comment by bonzofenix** [comment]
Built this image in the meantime to use the cf cli v7:

https://hub.docker.com/r/bonzofenix/cf-resource

usage:

```
...

resource_types:
- name: cf
  type: registry-image
  source:
    repository: bonzofenix/cf-resource
```
